display.o: display.c display.h ../sysdefs.h ../core/lpc134x.h \
 ../core/sysdefs.h ../core/../sysdefs.h ../core/projectconfig.h \
 ../core/lpc134x.h ../core/ssp/ssp.h ../core/projectconfig.h \
 ../core/gpio/gpio.h ../core/gpio/gpio.h ../basic/basic.h \
 ../core/adc/adc.h ../basic/uuid.h ../basic/idle.h ../basic/simpletime.h \
 ../basic/config.h ../usb/usbmsc.h
render.o: render.c ../sysdefs.h render.h display.h fonts.h decoder.h \
 fonts.h ../basic/basic.h ../core/gpio/gpio.h ../core/projectconfig.h \
 ../core/lpc134x.h ../core/sysdefs.h ../core/../sysdefs.h \
 ../core/projectconfig.h ../core/adc/adc.h ../basic/uuid.h \
 ../basic/idle.h ../basic/simpletime.h fonts/smallfonts.h ../lcd/fonts.h \
 ../filesystem/ff.h ../filesystem/integer.h ../filesystem/ffconf.h \
 render.h
decoder.o: decoder.c fonts.h ../sysdefs.h render.h display.h fonts.h
backlight.o: backlight.c ../core/lpc134x.h ../core/sysdefs.h \
 ../core/../sysdefs.h ../core/projectconfig.h ../core/lpc134x.h \
 ../sysdefs.h ../core/gpio/gpio.h ../core/projectconfig.h \
 ../basic/basic.h ../core/adc/adc.h ../basic/uuid.h ../basic/idle.h \
 ../basic/simpletime.h
print.o: print.c display.h ../sysdefs.h render.h display.h fonts.h \
 fonts.h print.h fonts/smallfonts.h ../lcd/fonts.h
image.o: image.c ../core/sysinit.h ../core/projectconfig.h \
 ../core/lpc134x.h ../core/sysdefs.h ../core/../sysdefs.h \
 ../core/gpio/gpio.h ../core/projectconfig.h ../core/systick/systick.h \
 ../basic/basic.h ../core/adc/adc.h ../basic/uuid.h ../basic/idle.h \
 ../basic/simpletime.h ../lcd/lcd.h ../lcd/backlight.h ../lcd/decoder.h \
 ../lcd/display.h ../sysdefs.h ../lcd/render.h ../lcd/display.h \
 ../lcd/fonts.h ../lcd/fonts/smallfonts.h ../lcd/fonts.h ../lcd/o.h \
 ../filesystem/ff.h ../filesystem/integer.h ../filesystem/ffconf.h
o.o: o.c display.h ../sysdefs.h o.h
invaders.o: fonts/invaders.c fonts/invaders.h ../lcd/fonts.h ../sysdefs.h
ubuntu18.o: fonts/ubuntu18.c fonts/ubuntu18.h ../lcd/fonts.h ../sysdefs.h
ubuntu36.o: fonts/ubuntu36.c fonts/ubuntu36.h ../lcd/fonts.h ../sysdefs.h
smallfonts.o: fonts/smallfonts.c fonts/smallfonts.h ../lcd/fonts.h \
 ../sysdefs.h
orbitron14.o: fonts/orbitron14.c fonts/orbitron14.h ../lcd/fonts.h \
 ../sysdefs.h
ubuntu29.o: fonts/ubuntu29.c fonts/ubuntu29.h ../lcd/fonts.h ../sysdefs.h
