##########################################################################
# User configuration and firmware specific object files	
##########################################################################

OBJS =

OBJS += display.o
#OBJS += render.o
#OBJS += decoder.o
#OBJS += backlight.o
#OBJS += print.o
#OBJS += image.o
#OBJS += o.o

LIBNAME=lcd

##########################################################################
# GNU GCC compiler flags
##########################################################################
ROOT_PATH?= ..
INCLUDE_PATHS = -I$(ROOT_PATH) -I../core -I.

include $(ROOT_PATH)/Makefile.inc

##########################################################################
# Actual work
##########################################################################

include $(ROOT_PATH)/Makefile.util
